name: Compile-Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_make
      run: sudo apt-get install make
    - name: get_gcc_arm_none_eabi
      run: sudo apt-get install gcc-arm-none-eabi
    - name: Compile
      run: make -C 3_Implementation/Debug/ all
